### ISSUE TITLE
Cannot show the percent sign in figure

### ISSUE THREAD

**Issue by ShaofengZou** [garrettj403/SciencePlots#115]
### Environment

```Python console
System: macOS-14.0-arm64-arm-64bit
Python: 3.9.6 (default, Jun 28 2021, 19:24:41) 
[Clang 12.0.5 (clang-1205.0.22.9)]
SciencePlots: 2.1.1
Matplotlib: 3.5.0
LaTeX distro:
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

### Affected styles

```Python console
['science',  'grid']
```

### Describe the issue here

Cannot show the percent sign in the figure legend.

### How can we replicate it? What have you tried? Please, add a reproducible example

plt.plot(x, y, label='{:.1f}%'.format(45))

**Comment by echedey-ls** [comment]
See this link https://tex.stackexchange.com/questions/280924/how-to-insert-symbol-in-a-statement-without-intending-comment#280925
________________________________
From: ShaofengZou ***@***.***>
Sent: Thursday, April 18, 2024 6:04:52 AM
To: garrettj403/SciencePlots ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [garrettj403/SciencePlots] Cannot show the percent sign in figure (Issue #115)


Environment

System: macOS-14.0-arm64-arm-64bit
Python: 3.9.6 (default, Jun 28 2021, 19:24:41)
[Clang 12.0.5 (clang-1205.0.22.9)]
SciencePlots: 2.1.1
Matplotlib: 3.5.0
LaTeX distro:
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04

Affected styles

['science',  'grid']

Describe the issue here

Cannot show the percent sign in the figure legend.

How can we replicate it? What have you tried? Please, add a reproducible example

plt.plot(x, y, label='{:.1f}%'.format(45))

Extra info

No response

**Comment by echedey-ls** [comment]
Just in case, you had to use `\%` where you wanted `%`.

Closing as completed due to inactivity.
