### ISSUE TITLE
Legends overlap with plot and looks ugly

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [garrettj403/SciencePlots#15]
code attached. Any way to improve?
![test](https://user-images.githubusercontent.com/40440788/86319796-58440d00-bc03-11ea-90bf-6d36ec4723a9.png)

[test.py.zip](https://github.com/garrettj403/SciencePlots/files/4862163/test.py.zip)

**Comment by resodchym** [comment]
I think it's because your figure is really small for the legend.

You could just make your figure bigger with something like
`plt.figure(figsize=(10,10), dpi = 200)` 
![image](https://user-images.githubusercontent.com/60574026/86343050-b6e7a600-bc58-11ea-8db3-5156480996a0.png)

Or just put legends outside with something like
`leg = plt.legend(handles=[l1, l2, l3], loc='best', bbox_to_anchor=(1.04, 0.5))`
![image](https://user-images.githubusercontent.com/60574026/86343162-e0a0cd00-bc58-11ea-8056-b87830744c4c.png)

**Comment by garrettj403** [comment]
Hi @2young-2simple-sometimes-naive 

You have a couple options:

- Add a frame: ``plt.legend(frameon=True)``

- Make your font size smaller: ``plt.legend(frameon=True, fontsize=7)``

- Move your legend outside of the plot (following @resodchym's advice)
