### ISSUE TITLE
Is it possible to add support for CJK fonts

### ISSUE THREAD

**Issue by Alraemon** [garrettj403/SciencePlots#16]
Currently, the legends & labels written in CJK characters can not be properly displayed, can this issue be fixed, or any way to override something to get it displayed ?

**Comment by garrettj403** [comment]
I don't have any experience with CJK fonts, but I think that it's probably something to do with the Latex font rendering.

Does it work properly if you disable Latex?

```python
plt.style.use(['science', 'no-latex'])
```

**Comment by Alraemon** [comment]
Unlucky, it seems to be useless. When using LaTeX, I notice it's using pdfTeX, which poorly supports CJK rendering and hard to tweak. However, using no-latex still can not fix the issue directly, but having some tweaks in .mlpstyle could be helpful. I will try fixing it & make a PR later. Hopefully, I will also try fixing LaTeX rendering issue.  :D

**Comment by Alraemon** [comment]
> I don't have any experience with CJK fonts, but I think that it's probably something to do with the Latex font rendering.
> 
> Does it work properly if you disable Latex?
> 
> ```python
> plt.style.use(['science', 'no-latex'])
> ```
> 

Unlucky, it seems to be useless. When using LaTeX, I notice it's using pdfTeX, which poorly supports CJK rendering and hard to tweak. However, using no-latex still can not fix the issue directly, but having some tweaks in .mlpstyle could be helpful. I will try fixing it & make a PR later. Hopefully, I will also try fixing LaTeX rendering issue. :D

**Comment by garrettj403** [comment]
Hi @Alraemon 

Did you have any luck getting this to work?

**Comment by Hsins** [comment]
Hi @garrettj403

There is no font fallback implementation in `matplotlib` so that it can't properly display the CJK characters even though we disable the LaTeX rendering engine. Moreover, we can only use a certain font support CJK and Latin characters for mixed texts (check this [issue in `matplotlib`](https://github.com/matplotlib/matplotlib/issues/18883) for more information).

There would be two possible ways to use CJK for plotting:

1. Disable LaTeX rendering engine and choose the font which supports both CJK and Latin characters.
2. Use pgf rendering but switch the TeX engine to `XeLaTeX` or `LuaLaTeX`. It's more complex and something infrastructure should be setup.

---

To use mixed CJK characters and Latins characters with `XeLaTeX` or `LuaLaTeX` engine, we need to use the `fontspec` or `babelfont` packages (check [this question on stackexchange](https://tex.stackexchange.com/questions/530822/fontspec-babelfont-mixing-chinese-and-english-latin-font-different-in-chine)):

There is an example in [the Colab jupyter notebook](https://colab.research.google.com/drive/15fZBqA4lrUf_D6BYx5CerRepxupG9Rst?usp=sharing)

```python
matplotlib.use('pgf') # stwich backend to pgf
matplotlib.rcParams.update({
    "pgf.texsystem": "xelatex",
    "text.usetex": True,    # use default xelatex
    "pgf.rcfonts": False,   # turn off default matplotlib fonts properties
    "pgf.preamble": [
        r'\usepackage{fontspec, xeCJK}',
        r'\setmainfont{Latin Modern Roman}',# EN fonts Romans
        r'\setCJKmainfont{SimHei}',# set CJK fonts as SimSun
        r'\setCJKsansfont{SimHei}',
        r'\newCJKfontfamily{\Song}{SimSun}',
        ]
})
```

The script above would export the `sample.pdf` inside that work folder. I upload the screenshot of the figure inside that file:

![image](https://user-images.githubusercontent.com/26391143/98040713-ae4bea00-1e5b-11eb-82c5-cdb5f87f722a.png)

**Comment by garrettj403** [comment]
Update
--------

@Hsins made a pull request to add support for CJK fonts (see #29). The new `cjk-fonts` style requires some additional font packages. Instructions on how to install these packages can be found in the [FAQ section of the README](https://github.com/garrettj403/SciencePlots#faq).

Example 14 provides an example of this style:

![](https://raw.githubusercontent.com/garrettj403/SciencePlots/master/examples/figures/fig14.jpg)

The style works well with SC/TC/JP characters, but there are some errors with Korean characters (see discussion in #29).

I reopened this issue in case anyone requires Korean characters.

**Comment by Hsins** [comment]
Hi @garrettj403 

I have tried again to deal with the Korean characters, it seems that errors occur when the character `전` in texts (no matter users use the `Noto Serif CJK TC`, `Noto Serif CJK JP`, `Noto Serif CJK KR` or `Noto Serif CJK SC`). I would effort to find another open-source Korean Font to apply.

----

By the way, I must point out that the given list of fonts below is nonsense in most cases (and sorry for that I push it in previous commits) because of the lack of font fallback mechanism in `matplotlib`.

```
font.serif : Noto Serif CJK TC, Noto Serif CJK SC, Noto Serif CJK JP, Noto Serif CJK KR, Times New Roman
```

The `matplotlib` just finds the font in that font list and apply the first valid (means it can be found in the given path) one to all characters in the given string. So the style `cjk-fonts` would only apply the `Noto Serif CJK TC` fonts for rendering characters if it can be found. And the following fonts would be ignored.

Moreover, there are some differences in those Noto Fonts even though each font supports the charsets in other CJK languages:

<p align="right">
Ref: https://ibe.tw/noto-font/
</p>
<p align="center">
  <img src="https://user-images.githubusercontent.com/26391143/98280197-00b11600-1fd6-11eb-84c8-70c8fc88a45f.png">
</p>

Would you mind to separate the `cjk-fonts` style into `cjk-tc-fonts`, `cjk-sc-fonts`, `cjk-jp-fonts` and `cjk-kr-fonts` styles?

**Comment by garrettj403** [comment]
Okay, I split `cjk-fonts` into separate files in commit 4204854.

Note: When I run example 14, I get the following error message:

    'NotoSerifCJKtc-Regular.otf' can not be subsetted into a Type 3 font. The entire font will be embedded in the output.

This means that the PDF files end up being ~20 MB. Do you have the same issue?

**Comment by Hsins** [comment]
I have that same issue too but the problem can't be solved ourselves. 

The `matplotlib` use Type 3 font to produce PDF document by default to reduce the file size. (The disadvantage of Type 3 font is that it can not be edited by a PDF editor such as Adobe Acrobat Pro. The “advantage” is that the produced PDF is small in size.)

But it failed to subsetted the CJK fonts we used. The result would be embedded those fonts into the output file and what the sad news is all the CJK fonts are HUGE. This may as same as the result when we need to use FontType 42 and it make the size of PDF file large.

---

For someone who wants to reduce the size of PDF file, just follow the solutions [here](https://stackoverflow.com/questions/10450120/optimize-pdf-files-with-ghostscript-or-other/14384178#14384178) to convert the PDF file to Ghostscript file then convert it back.

```bash
$ pdf2ps file.pdf file.ps
$ ps2pdf -dPDFSETTINGS=/prepress file.ps file-optimized.pdf
```

The option -dPDFSETTINGS defines the quality of the produced PDF. Possible options and explanations are listed below:


- `-dPDFSETTINGS=/screen`: screen-view-only quality, 72 dpi images
- `-dPDFSETTINGS=/ebook`: low quality, 150 dpi images
- `dPDFSETTINGS=/printer`: high quality, 300 dpi images
- `dPDFSETTINGS=/prepress`: high quality, color preserving, 300 dpi imgs
- `dPDFSETTINGS=/default`: almost identical to /screen

**Comment by garrettj403** [comment]
I created a new release (v1.0.7) which includes limited support for CJK characters. There is still the issue that CJK pdf figures are very large but you can follow the instructions above (from @Hsins) to reduce the size of those figures. I don't think there is anything we can do to fix this.

Note:
- Korean characters seem to work now ([see Fig. 14d](https://raw.githubusercontent.com/garrettj403/SciencePlots/master/examples/figures/fig14d.jpg))
- For me, everything works on both macOS and Windows (using Windows Subsystem for Linux)

I'll close this issue for now, but feel free to reopen if there are any more problems or ways to improve CJK support.
