### ISSUE TITLE
x-axis order problem

### ISSUE THREAD

**Issue by linnaeushuang** [garrettj403/SciencePlots#31]
Hi,
thanks for your work.
My x-axis is [100, 90, ..., 20, 10],
but when I run the following code
```
x-axis=[ i for i in reversed(range(10,101,10))]
with plt.style.context(['science']):
    fig,ax=plt.subplots()
    ax.plot(x-axis,y-axis)
```
the x-axis your figure showed me is [10, 20, ..., 90, 100].
How can i solve this problem?
wait for your repeat :)

**Comment by Hsins** [comment]
Hey! You're just in the wrong place. It's a question about how to use `matplotlib` instead of any problems with `SciencePlots`. 

You would know what happened here if you remember the Cartesian coordinate system concepts taught in your school time. Let me show you in brief. The figure1 and figure2 shown below are given the same values of `y` but different values of `x`. What the [`matplotlib.pyplot.plot()`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html#matplotlib-pyplot-plot) method would do is plotting the y versus x as lines (the pair of points in the Cartesian coordinate system).

### Figure 1
 
<img align="right" width="200" src="https://user-images.githubusercontent.com/26391143/100554906-267ac380-32d3-11eb-9b5b-a58deffe14f7.png">

```python
x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]
with plt.style.context(['science']):
    fig, ax = plt.subplots()
    ax.plot(x, y)
    plt.show()
```

### Figure 2

<img align="right" width="200" src="https://user-images.githubusercontent.com/26391143/100554952-82dde300-32d3-11eb-8289-c0337d899c39.png">

```python
x = [5, 4, 3, 2, 1]
y = [10, 20, 30, 40, 50]
with plt.style.context(['science']):
    fig, ax = plt.subplots()
    ax.plot(x, y)
    plt.show()
```

As the result, you don't need to reverse your list but use the `ax.set_xlim()` method to change the direction of the x-axis. Just use the `ax.set_xlim()` method to achieve it, you can see an example in [Invert Axes](https://matplotlib.org/3.1.1/gallery/subplots_axes_and_figures/invert_axes.html).

<img align="right" width="200" src="https://user-images.githubusercontent.com/26391143/100555266-40b5a100-32d5-11eb-9fb1-a8b212c477a5.png">

```python
x = list(range(10, 101, 10))
y = list(range(10, 101, 10))
with plt.style.context(['science']):
    fig, ax = plt.subplots()
    ax.plot(x, y)
    ax.set_xlim(max(x), min(x))
    plt.show()
```

**Comment by linnaeushuang** [comment]
wow, thanks a lot!
