### ISSUE TITLE
IEEE cycler limit

### ISSUE THREAD

**Issue by eneriz-daniel** [garrettj403/SciencePlots#33]
Hi! Just discovered this repo and love how helpful it is.

I've noticed the IEEE style has a detail that is annoying me. The default plot styles are this ones:
![ieee-default](https://user-images.githubusercontent.com/57150162/111449610-d7389180-870f-11eb-8eaf-c7932fb66655.png)

So it only allows up to 4 different plot styles. I've tried to change the cycles order using
```
from cycler import cycler
plt.rcParams.update({"axes.prop_cycle": cycler('linestyle', ['-', '--', ':', '-.'])*cycler('color', ['k', 'r', 'b', 'g'])})
```
to get the linestyles to iterate over the colors, creating up to 16 new ploting styles.
![ieee-new-cycler](https://user-images.githubusercontent.com/57150162/111450141-62b22280-8710-11eb-86bf-1b87a5f62c05.png)

Maybe you want to change it in the repo.

Thanks for sharing your work!

**Comment by garrettj403** [comment]
Hi @eneriz-daniel, I'm glad you find SciencePlots useful!

The IEEE style is a bit difficult to design because the plot should be readable in black & white, meaning that all of the line styles should be different. In your example, the solid black, red, blue and green lines will look identical in B&W. In Matplotlib, there are only 4 different line styles which limits the total number of lines in B&W to 4.

If you don't care about B&W readability, you can always override the `ieee` color cycle:
```python
plt.style.use(['science', 'ieee', 'std-colors'])
```
<img src="https://github.com/garrettj403/SciencePlots/raw/master/examples/figures/fig2b.jpg" width="500">

In this example, we still get the formatting of the ``ieee`` style (figure size, font, etc.) but ``std-colors`` overrides the ``ieee`` color cycle.

Note: ``std-colors`` isn't in the latest release yet. You need to install from the GitHub repo.

**Comment by eneriz-daniel** [comment]
That's true, hadn't thought in the B&W compatibility. Thanks for your suggestion of `std-colors`.
