### ISSUE TITLE
fig_width problem

### ISSUE THREAD

**Issue by lupupu** [garrettj403/SciencePlots#50]
I found that I couldn't control the width of the figure. Did I do something wrong?

### code
```Python
import numpy as np
import matplotlib.pyplot as plt


def function(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))


pparam = dict(xlabel='Voltage (mV)', ylabel='Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science']):
    fig_width = 24 / 2.54  # 24cm
    fig_height = 6 / 2.54  # 6cm
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, function(x, p), label=p)
    ax.legend(title='Order')
    ax.autoscale(tight=True)
    ax.set(**pparam)
    fig.savefig('fig1.pdf')
    fig.savefig('fig1.jpg', dpi=300)
```

### result
<img width="1116" alt="宽度不对" src="https://user-images.githubusercontent.com/17425858/135744121-638dfa17-8761-4b39-a8c1-c2e7de0b6745.png">
The width of figure is not 24cm, but 20.09cm.

**Comment by Hsins** [comment]
Actually, this is not an issue about SciencePlots but Matplotlib. I saw that you're using `subplots` so just added following code before save figures:

```python
fig.subplots_adjust(top=1.0, bottom=0, right=1.0, left=0, hspace=0, wspace=0) 
```

So that Matplotlib will correctly outputs the figure containing an image with exact size.

Check [this question and answers on stackoverflow](https://stackoverflow.com/questions/13714454/specifying-and-saving-a-figure-with-exact-size-in-pixels) for more information.
