### ISSUE TITLE
Documentation for SciencePlots

### ISSUE THREAD

**Issue by Hsins** [garrettj403/SciencePlots#51]
Hi, @garrettj403,

Discovering that the README file is getting longer and longer, I would like to create a documentation site for SciencePlots. Just use the [sphinx](https://www.sphinx-doc.org/en/master/) for generating and [GitHub Actions](https://github.com/features/actions) for deploying. How do you think?

**Comment by echedey-ls** [comment]
Just wanted to comment that I'm all for doing it, and in fact I started working on it some time ago, we can autogen the library for each style, which I believe would be of help. Also because that also means new contributors can update the indexes in the Sphinx source, instead of us making them update the readme, then go to the wiki, update it...
