### ISSUE TITLE
findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.

### ISSUE THREAD

**Issue by iDTer** [garrettj403/SciencePlots#58]
os: win10
SciencePlots v1.0.9
matplotlib 3.3.0
python 3.8

I have put the NotoSerifSC fonts into "..\site-packages\matplotlib\mpl-data\fonts\ttf" and also try the following command:
`import matplotlib.font_manager as fm
fm._rebuild()`

but still report "findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.".

**Comment by iDTer** [comment]
Or how can I set the ['serif'] to ['sans serif']?

Thank you for any help!!!

**Comment by G0K0URURI** [comment]
This may be because you don't install the corresponding font.

I use matplotlib-3.5.2, and then meet similar problem with you:
```
findfont: Font family ['serif'] not found. Falling back to DejaVu Sans. 
findfont: Generic family 'serif' not found because none of the following families were found: Times
```
I solve the problem by downloading the corresponding .ttf file and copying it to the 'my_python_path/site-packages/matplotlib/mpl-data/fonts/ttf/'
As I need to install Times font, I download the .ttf file from [https://www.dafontfree.net/times-regular/f145546.htm](url) and copy it to 'my_python_path/site-packages/matplotlib/mpl-data/fonts/ttf/'. After that, I delete the cache of matplotlib, which could be found by
```
import matplotlib
matplotlib.get_cachedir()
```

I hope it would be helpful for you : )

**Comment by hh-wu** [comment]
You can use the following code to avoid warning in win10 without calling latex.

```python
plt.style.use(['science', 'ieee', 'no-latex'])
matplotlib.rc('font', family='times new roman')
```

**Comment by zzwu29** [comment]
您好，您的邮件我已经收到，会尽快阅读并回复！
                                                                               zzWu

**Comment by echedey-ls** [comment]
Thank you everyone for the contribution.
Closing as resolved, since no more reports of the problem were made, I assume it did work.
