### ISSUE TITLE
OSError: 'science' not found in the style library

### ISSUE THREAD

**Issue by rmastand** [garrettj403/SciencePlots#85]
I am using SciencePlots 2.0. While I am including 

```
import scienceplots
import matplotlib.pyplot as plt
plt.style.use('science')
```

in my header, I'm still getting the error
`OSError: 'science' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
`.

**Comment by echedey-ls** [comment]
Sorry, I can't reproduce given that. Are you sure you are using the version v2.x.x?
Check version with `python3 -m pip show scienceplots`
Upgrade with `python3 -m pip install --upgrade scienceplots`

Does it work for you?

**Comment by echedey-ls** [comment]
Also, check you installed SciencePlots in the same Python as your notebook or IDE is using. Do `python3 -V` to show the version of the python the console is running, and check the configuration of VSCode, Jupyter, whatever you use to match it, or run a script with
```python
import sys
print(sys.version)
```
to show it.

If the problem persists, remember to share your device OS, Python version and whatever else you think might help us. I believe the problem is that there are many Python distributions installed on your system, and you are installing on one the v2.x.x which shouldn't have that problem; and the IDE you use is picking one that hasn't the newer SciencePlots.

This links should give you a hint to know if that might be the cause.
* [Python versions on Windows](https://stackoverflow.com/questions/53312590/how-can-i-check-all-the-installed-python-versions-on-windows)
* [Python versions on Linux](https://www.cyberithub.com/how-to-check-all-the-python-versions-installed-on-linux/#Method_1_Using_whereis_command)

**Comment by echedey-ls** [comment]
Could you solve it?

**Comment by rmastand** [comment]
Hi all -- the issue was actually due to path confusion with my latex distribution. All is working!
