### ISSUE TITLE
About use this tool in win10 with RuntimeError

### ISSUE THREAD

**Issue by datamonday** [garrettj403/SciencePlots#9]
First, thanks for @garrettj403 perfect work, it is very useful.

-----------------------------------------------------------------------------------------
If not install LaTeX in win10, run examples in this repo will get an error:
"RuntimeError: Failed to process string with tex because latex could not be found"

-----------------------------------------------------------------------------------------
Just need to install LaTeX and add 'path\texstudio.exe' to systerm enviroment PATH
(Note1: Need to install MiKTex and LaTeX, The following installation package will provide guidelines.)
(Note2:  Selecting for all users when installing MiKTex will automatically add MiKTex to the system environment variables PATH)

-----------------------------------------------------------------------------------------
the tex download: http://www.tug.org/

-----------------------------------------------------------------------------------------
I tested this tool in Jupyter notebook and it works very well.
I hope this suggestion can help friends who encounter this problem.

**Comment by garrettj403** [comment]
Hi @datamonday, 

Thanks for the tip! I'll add this to the README. 

I'm glad you find SciencePlots useful.

**Comment by Ehliu** [comment]
helpful!

**Comment by caijigiser** [comment]
I got the note and downloaded miktex on Windows 11, but the error still exists. Could you please give more details?

**Comment by echedey-ls** [comment]
@caijigiser since this package just provides styles for Matplotlib, we don't really do support for these kind of requests. However, for some obvious reasons, we've got some references that can help you:

- https://github.com/garrettj403/SciencePlots/wiki/FAQ#installing-latex (you come from there, I suppose)
- Might be worth reading https://matplotlib.org/stable/users/explain/text/usetex.html, although to be fair it does not help much
- You can check whether LaTeX is well integrated with the command `latex -v` on command line
- Rebooting may be worth, just to make sure all environment variables are updated and the installation has finished.
- I don't have Win11, so if it's an issue in that platform version I can't give more advice.

**Comment by caijigiser** [comment]
> @caijigiser since this package just provides styles for Matplotlib, we don't really do support for these kind of requests. However, for some obvious reasons, we've got some references that can help you:
> 
> * https://github.com/garrettj403/SciencePlots/wiki/FAQ#installing-latex (you come from there, I suppose)
> * Might be worth reading https://matplotlib.org/stable/users/explain/text/usetex.html, although to be fair it does not help much
> * You can check whether LaTeX is well integrated with the command `latex -v` on command line
> * Rebooting may be worth, just to make sure all environment variables are updated and the installation has finished.
> * I don't have Win11, so if it's an issue in that platform version I can't give more advice.

Two days later, the script is working well!  Maybe as you said the environment variables had to be updated, rebooting would help! Thanks for your reply!
