### ISSUE TITLE
How to implement a two-column chart

### ISSUE THREAD

**Issue by 233thzhang** [garrettj403/SciencePlots#99]
![image](https://github.com/garrettj403/SciencePlots/assets/59596762/5f234d24-d95f-408a-a607-8caea156fd28)
I would like to know if scienceplots can achieve this effect.

**Comment by echedey-ls** [comment]
The 2x2 plot grid pretty easy to look for in the Internet.
https://matplotlib.org/stable/tutorials/intermediate/arranging_axes.html#sphx-glr-tutorials-intermediate-arranging-axes-py

For the styles, I think you can't apply a style for each one, but with `axes.plot` you can set the color of the line. If you want to automate setting the colours, you should use a color cycler. You can browse current styles to get inspired.

Just make use of the science style since it already has the small and big ticks.
